# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: yarn build

      # Runs a set of commands using the runners shell
      - name: Commit build
        run: |
          cp -b ../beaudar.json .,
          git init
          git commit -m 'deploy'
          git commit -m 'deploy'
          git remote -v
          
      - name: Push Remote Origin
        run: git push -f git@github.com:crossgate-book/crossgate-book.github.io.git master
      
